server.port=9090
logging.level.org.springframework.data.elasticsearch=DEBUG
logging.level.co.elastic.clients=DEBUG

#spring.elasticsearch.uris=http://localhost:9200
#spring.elasticsearch.uris=https://my-elasticsearch-project-ee92d9.es.us-east-1.aws.elastic.cloud:443

# Elastic Cloud connection
#elasticsearch.cloud.endpoint=https://my-elasticsearch-project-ee92d9.es.us-east-1.aws.elastic.cloud:443
#elasticsearch.cloud.token=Vk1NWXM1d0IxQlptX0ZCbm5VWnc6dFZ4aUZTNFJDbHYwZy1mNFc5OGxCZw==

#spring.elasticsearch.uris=https://my-elasticsearch-project-ee92d9.es.us-east-1.aws.elastic.cloud:443
#spring.elasticsearch.api-key=Vk1NWXM1d0IxQlptX0ZCbm5VWnc6dFZ4aUZTNFJDbHYwZy1mNFc5OGxCZw==

#spring.elasticsearch.uris=https://my-elasticsearch-project-ee92d9.es.us-east-1.aws.elastic.cloud:443
#spring.elasticsearch.api-key=Vk1NWXM1d0IxQlptX0ZCbm5VWnc6dFZ4aUZTNFJDbHYwZy1mNFc5OGxCZw==

spring.elasticsearch.uris=https://my-elasticsearch-project-ee92d9.es.us-east-1.aws.elastic.cloud:443
spring.elasticsearch.api-key=Vk1NWXM1d0IxQlptX0ZCbm5VWnc6dFZ4aUZTNFJDbHYwZy1mNFc5OGxCZw==


#Kibana=https://my-elasticsearch-project-ee92d9.kb.us-east-1.aws.elastic.cloud